services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    entrypoint: /entrypoint.sh
    volumes:
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./docker/homeassistant.tar.gz:/homeassistant.tar.gz
     # - ./docker/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
